# https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swiftlint
# https://github.com/realm/SwiftLint

included:
  - Sources

excluded:
  - .build/
  - build/

disabled_rules:
  - trailing_comma
